const gameVariables = {
  scoreTag: document.getElementById("score"),
  userNameTag: document.getElementById("userName"),
  enemiesTag: document.getElementById("enemies"),
  lifeTag: document.getElementById("life"),
  blackScreen: document.querySelector(".blackScreen"),
  loseTag: document.getElementById("lose"),
  winTag: document.getElementById("win"),
  btnRestart: document.querySelector("#reload"),
  progScreen: document.getElementById("container-prog"),
  progBar: document.querySelector(".progress-bar"),
  score: 0,
  userName: "Parker",
  guards: 0,
  life: 100,
  armor: 100,
  scrollOffsetX: 0,
  scrollOffsetY: 0,
  isAreaLevelOneAdded: false,
  isAreaLevelTwoAdded: false,
};
